const cities = ['Aberdeen', 'Albany', 'Albuquerque', 'Alexandria', 'Anchorage', 'Appleton', 'Arlington', 'Asheville', 'Athens', 'Atlanta', 'Austin', 'Baltimore', 'Beaumont', '"Bel Air', 'Berkeley', 'Birmingham', 'Boston', 'Boulder', 'Buffalo', 'Burlington', 'Cambridge', 'Cary', 'Charleston', 'Charlotte', 'Chattanooga', 'Chicago', 'Cincinnati', 'Cleveland', 'Columbia', 'Concord', 'Dallas', 'Davenport', 'Dayton', 'Denver', 'Detroit', 'Durham', 'El Paso', 'Flint', 'Gainesville', 'Gastonia', 'Greensboro', 'Greenville', 'Hampton', 'Harrisburg', 'Henderson', 'Hickory', 'High Point', 'Hollywood', 'Honolulu', 'Houston', 'Indianapolis', 'Irving', 'Jacksonville', 'Jersey City', 'Kailua', 'Kansas City', 'Knoxville', 'Lancaster', 'Las Vegas', 'Lexington', 'Lincoln', 'Long Beach', 'Los Angeles', 'Louisville', 'Melbourne', 'Memphis', 'Miami', 'Milwaukee', 'Minneapolis', 'Monroe', 'Myrtle Beach', 'Nashville', 'New Orleans', 'New York', 'Newark', 'Norfolk', 'Oakland', 'Oklahoma City', 'Omaha', 'Ontario', 'Orlando', 'Pasadena', 'Philadelphia', 'Phoenix', 'Pittsburgh', 'Portland', 'Raleigh', 'Richmond', 'Roanoke', 'Rochester', 'Sacramento', 'Saint Louis', 'San Antonio', 'San Diego', 'San Francisco', 'San Jose', 'Savannah', 'Scranton', 'Seattle', 'Spartanburg', 'Springfield', 'St. Louis', 'Syracuse', 'Tacoma', 'Tallahassee', 'Tampa', 'Topeka', 'Trenton', 'Tucson', 'Tulsa', 'Vancouver', 'Waco', 'Washington', 'Wichita', 'Wilmington', 'Winston', 'Yonkers' ];

const letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'];

const starWarsPlanets = ['Tatooine', 'Coruscant', 'Hoth', 'Endor', 'Naboo', 'Alderaan', 'Mustafar', 'Kamino', 'Bespin', 'Kashyyyk', 'Dagobah', 'Jakku', 'Geonosis', 'Yavin', 'Corellia', 'Mandalore', 'Polis Massa', 'Felucia', 'Mygeeto', 'Utapau', 'Death Star', 'Rebel Fleet', 'Asteroid Belt']

const middleEarthCities = ['Misty Mountains', 'Mount Doom', 'Gondor', 'Minas Tirith', 'Helm\'s Deep', 'Isengard', 'Lothlórien', 'Mirkwood', 'Rivendell', 'Shire', 'Rohan', ' White Mountains', 'Moria', 'Dead Marshes', 'Black Gate', 'Prancing Pony', 'Weathertop', 'Bree', 'Fangorn', 'Cirith Ungol', 'Erebor', 'Gladden Fields', 'Grey Havens'  ]


const nodeNameSeeds = [cities, letters, starWarsPlanets, middleEarthCities]

export default nodeNameSeeds